### ISSUE TITLE
blessed + websockets + xterm.js

### ISSUE THREAD

**Issue by sigmareaver** [embarklabs/neo-blessed#17]
I've been trying to get this working for a while, to no avail. This is sort of a last resort, but I don't know where else to go.

For the server, I am using websockets (ws://) with http, and blessed.
See here: https://pastebin.com/aE0LHCZ0

For the client, I have my browser (Firefox) running xterm.js to create a terminal in the browser.
See here: https://pastebin.com/aH9sbk5f

I can get a connection established, and both ends can send/receive the 'message' event, but nothing shows up when I do screen.render(). Can someone help me get this working?

**Comment by mark-zarandi** [comment]
@sigmareaver any progress on this?

**Comment by sigmareaver** [comment]
I had to give up on that. It's been so long, so I may be wrong here, but if I recall correctly (and that's a big if at this point), browser security wasn't allowing websockets to be used the way I wanted to use it.
